Controllers/FinanceController.cs
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using LPE_Magac.Models;
using LPE_Magac.ViewModel;
using System.Data.Entity.Validation;
using System.Data.Entity;

namespace LPE_Magac.Controllers
{
    [AllowAnonymous]
    public class FinanceController : Controller
    {
        Db_LPE_MagacEntities db = new Db_LPE_MagacEntities();
        // GET: Finance
        public ActionResult Index()
        {
            var IOtable = new FundsModel
            {
                Incomes = db.tbl_fund_income.ToList(),
                Outcomes = db.tr_fund_outcome.ToList(),
                Requests = db.tr_fund_request.ToList()
            };
            return View(IOtable);
        }
        public ActionResult GetDataIncome()
        {
            var query = db.tbl_fund_income.GroupBy(p => p.date_income.Value.Year)
                .Select(g => new { date = g.Key, count = g.Sum(x => x.total_fund_income) }).OrderBy(x => x.date).ToList();
            return Json(query, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDataOutcome()
        {
            var query = db.tr_fund_outcome.GroupBy(p => p.date_outcome.Value.Year)
                .Select(g => new { date = g.Key, count = g.Sum(x => x.total_fund_outcome) }).OrderBy(x => x.date).ToList();
            return Json(query, JsonRequestBehavior.AllowGet);
        }
        //====================================================================
        //Fund Table
        public ActionResult FundTable()
        {
            var IOtable = new FundsModel
            {
                Incomes = db.tbl_fund_income.ToList(),
                Outcomes = db.tr_fund_outcome.ToList()
            };
            return View(IOtable);     
        }
        //====================================================================
        public ActionResult IncomeEdit(int id)
        {
            return View(db.tbl_fund_income.Where(x => x.pk_id_fund_income == id).FirstOrDefault());
        }
        public ActionResult IncomeDelete(int id)
        {
            return View(db.tbl_fund_income.Where(x => x.pk_id_fund_income == id).FirstOrDefault());
        }
        //==========================
        [HttpPost]
        public ActionResult IncomeEdit(int id, tbl_fund_income income)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    db.Entry(income).State = EntityState.Modified;
                    tbl_finance_report EditIncomeReport = db.tbl_finance_report.Where(x => x.fk_id_fund_income == id).FirstOrDefault();
                    EditIncomeReport.date_report = income.date_income;
                    db.Entry(EditIncomeReport).State = EntityState.Modified;
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("FundTable");
                }
                catch(Exception e) {
                    Db_LPE_MagacEntities db1 = new Db_LPE_MagacEntities();
                    tbl_log_history error = new tbl_log_history()
                    {
                        user_name = (string)Session["userName"],
                        fk_id_user = (int)Session["userID"],
                        Action_date = DateTime.Now,
                        ErrorMessage = "Page Error : IncomeEdit, " + e.Message
                    };
                    db1.tbl_log_history.Add(error);
                    db1.SaveChanges();
                    Transaction.Rollback();
                }
            }
            return View(income);
        }
        [HttpPost]
        public ActionResult IncomeDelete(int id, tbl_fund_income income)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var removeeReport = db.tbl_finance_report.Where(x => x.fk_id_fund_income == id).FirstOrDefault();
                    db.tbl_finance_report.Remove(removeeReport);
                    var removeeIncome = db.tbl_fund_income.Where(x => x.pk_id_fund_income == id).FirstOrDefault();
                    db.tbl_fund_income.Remove(removeeIncome);
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("FundTable");
                }
                catch (Exception e)
                {
                    Db_LPE_MagacEntities db1 = new Db_LPE_MagacEntities();
                    tbl_log_history error = new tbl_log_history()
                    {
                        user_name = (string)Session["userName"],
                        fk_id_user = (int)Session["userID"],
                        Action_date = DateTime.Now,
                        ErrorMessage = "Page Error : IncomeDelete, " + e.Message
                    };
                    db1.tbl_log_history.Add(error);
                    db1.SaveChanges();
                    Transaction.Rollback();
                }
            }
            return View(income);
        }
        [HttpGet]
        public ActionResult FormIncome()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FormIncome(tbl_fund_income income)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    db.tbl_fund_income.Add(income);
                    tbl_finance_report inputdata = new tbl_finance_report
                    {
                        fk_id_fund_income = income.pk_id_fund_income,
                        date_report = income.date_income
                    };
                    db.tbl_finance_report.Add(inputdata);
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("FundTable");
                }
                catch (Exception e)
                {
                    Db_LPE_MagacEntities db1 = new Db_LPE_MagacEntities();
                    tbl_log_history error = new tbl_log_history()
                    {
                        user_name = (string)Session["userName"],
                        fk_id_user = (int)Session["userID"],
                        Action_date = DateTime.Now,
                        ErrorMessage = "Page Error : FormIncome, " + e.Message
                    };
                    db1.tbl_log_history.Add(error);
                    db1.SaveChanges();
                    Transaction.Rollback();
                }
            }
            return View(income);
        }
        //====================================================================
        //public ActionResult OutcomeEdit(int id)
        //{
        //    return View(db.tr_fund_outcome.Where(x => x.pk_id_fund_outcome == id).FirstOrDefault());
        //}
        //public ActionResult OutcomeDelete(int id)
        //{
        //    return View(db.tr_fund_outcome.Where(x => x.pk_id_fund_outcome == id).FirstOrDefault());
        //}
        //==========================
        //[HttpPost]
        //public ActionResult OutcomeEdit(int id, tr_fund_outcome outcome)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        tbl_finance_report EditOutcomeReport = db.tbl_finance_report.Where(x => x.fk_id_fund_income == id).FirstOrDefault();
        //        EditOutcomeReport.date_report = outcome.date_outcome;
        //        db.Entry(outcome).State = EntityState.Modified;
        //        //EditOutcomeReport.balance = +(outcome.total_fund_outcome);
        //        db.Entry(EditOutcomeReport).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("FundTable");
        //    }
        //    return View(outcome);
        //}
        //[HttpPost]
        //public ActionResult OutcomeDelete(int id, tr_fund_outcome outcome)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var removeeOutcome = db.tr_fund_outcome.Where(x => x.pk_id_fund_outcome == id).FirstOrDefault();
        //        var removeeReport = db.tbl_finance_report.Where(x => x.fk_id_fund_income == id).FirstOrDefault();
        //        db.tbl_finance_report.Remove(removeeReport);
        //        db.tr_fund_outcome.Remove(removeeOutcome);
        //        db.SaveChanges();
        //        return RedirectToAction("FundTable");
        //     }
        //    return View(outcome);
        //}

        [HttpGet]
        public ActionResult FormOutcome()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FormOutcome(tr_fund_request request)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    tbl_invoice_finance invoice = new tbl_invoice_finance
                    {
                        fk_id_fund_request = request.pk_id_fund_request,
                        status_invoice_finance = "Send Dir"
                    };
                    db.tbl_invoice_finance.Add(invoice);
                    //===========
                    tbl_invoice_director invoiceDir = new tbl_invoice_director
                    {
                        fk_id_invoice_finance = invoice.pk_id_invoice_finance,
                        status_invoice_director = "App Fin"
                    };
                    db.tbl_invoice_director.Add(invoiceDir);
                    //===========
                    request.status_request = "Send Dir";
                    request.date_request = DateTime.Now;
                    db.tr_fund_request.Add(request);
                    //===========
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("ListRequest");

Controllers/TechnicianController.cs
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using LPE_Magac.Models;
using LPE_Magac.ViewModel;
using System.Data.Entity.Validation;
using System.IO;
using System.Data.Entity;

namespace LPE_Magac.Controllers
{
    [AllowAnonymous]
    public class TechnicianController : Controller
    {
        Db_LPE_MagacEntities db = new Db_LPE_MagacEntities();
        // GET: Technician
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult MyProfile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MyProfile(tbl_temp_user user)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    db.tbl_temp_user.Add(user);
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("index");
                }
                catch (Exception)
                {
                    Transaction.Rollback();
                }
            }
            return View(user);
        }
        //============Req Funds==============
        [HttpGet]
        public ActionResult RequestFunds()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RequestFunds(tr_fund_request request)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    tbl_invoice_finance invoice = new tbl_invoice_finance();
                    invoice.fk_id_fund_request = request.pk_id_fund_request;
                    invoice.status_invoice_finance = "Request";
                    db.tbl_invoice_finance.Add(invoice);
                    //===========
                    tbl_invoice_director invoiceDir = new tbl_invoice_director();
                    invoiceDir.fk_id_invoice_finance = invoice.pk_id_invoice_finance;
                    invoiceDir.status_invoice_director = "At Fin";
                    db.tbl_invoice_director.Add(invoiceDir);
                    //===========
                    request.status_request = "Send Fin";
                    request.date_request = DateTime.Now;
                    db.tr_fund_request.Add(request);
                    //===========
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("ListRequestFunds");
                }
                catch (Exception)
                {
                    Transaction.Rollback();
                }
            }
            return View(request);
        }

        public ActionResult ListRequestFunds()
        {
            List<tbl_invoice_director> directors = db.tbl_invoice_director.ToList();
            List<tbl_invoice_finance> invoice = db.tbl_invoice_finance.ToList();
            List<tr_fund_request> request = db.tr_fund_request.ToList();
            var ListRequest = from a in directors
                              join b in invoice on a.fk_id_invoice_finance equals b.pk_id_invoice_finance
                              join c in request on b.fk_id_fund_request equals c.pk_id_fund_request into table
                              from c in table.ToList()
                              orderby c.date_request descending
                              select new InvoiceModel
                              {
                                  Invoice_Director = a,
                                  Invoice_Finance = b,
                                  Fund_Request = c
                              };
            return View(ListRequest);
        }
        public ActionResult Guide()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        [HttpGet]
        public ActionResult SaveEdit()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveEdit(HttpPostedFileBase file, tbl_temp_user edited)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    tbl_temp_user inputdata = new tbl_temp_user();
                    if (file != null && file.ContentLength > 0)
                    {
                        string imgname = Path.GetFileName(file.FileName);
                        string ext = Path.GetExtension(imgname);
                        if (ext == ".jpg" || ext == ".png" || ext == ".jpeg" || ext == ".JPG" || ext == ".PNG" || ext == ".JPEG")
                        {
                            string imgpatch = Path.Combine(Server.MapPath("~/Content/images/avatar"), imgname);
                            file.SaveAs(imgpatch);
                            inputdata.temp_user_profile_picture = imgname;
                        }
                    }
                    inputdata.pk_id_temp_user = edited.pk_id_temp_user;
                    inputdata.temp_user_name = edited.temp_user_name;
                    inputdata.temp_user_password = edited.temp_user_password;
                    inputdata.temp_user_email = edited.temp_user_email;
                    inputdata.temp_user_position = edited.temp_user_position;
                    inputdata.temp_user_address = edited.temp_user_address;
                    inputdata.fk_id_user = edited.fk_id_user;
                    db.tbl_temp_user.Add(inputdata);
                    db.SaveChanges();
                    Transaction.Commit();
                    return View("Index");
                }
                catch (Exception)
                {
                    Transaction.Rollback();
                    edited.ErrorMessage = "Required field cannot be empty.";
                }
            }
            return View("MyProfile", edited);
        }
    }
}

Views/Shared/Error (1).cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>An error occurred while processing your request.</h2>
    </hgroup>
</body>
</html>

Views/Shared/Error(1).cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>An error occurred while processing your request.</h2>
    </hgroup>
</body>
</html>

Views/Shared/NavBarDirector.cshtml
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
    <div class="sidebar-collapse menu-scroll">
        <ul id="side-menu" class="nav">
            <div class="clearfix"></div>
            <li>
                <a href="@Url.Action("Index", "Director")">
                    <i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("FundTable", "Director")">
                    <i class="fa fa-database fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Funds</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("RequestFunds", "Director")">
                    <i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Request Funds</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Guide", "Director")">
                    <i class="fa fa-search fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Guide</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("About", "Director")">
                    <i class="fa fa-info fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">About</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Logout","Login")">
                    <i class="fa fa-key fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Logout</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

Views/Shared/NavBarFinance (1).cshtml
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
    <div class="sidebar-collapse menu-scroll">
        <ul id="side-menu" class="nav">
            <div class="clearfix"></div>

            <li>
                <a href="@Url.Action("Index", "Finance")">
                    <i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Dashboard</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("FundTable", "Finance")">
                    <i class="fa fa-database fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("ListRequest", "Finance")">
                    <i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Request Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("ReportFunds", "Finance")">
                    <i class="fa fa-file-o fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Report Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("User", "Finance")">
                    <i class="fa fa-user fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">User</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("LogHistory", "Finance")">
                    <i class="fa fa-history fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Log History</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("Guide", "Finance")">
                    <i class="fa fa-search fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Guide</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("About", "Finance")">
                    <i class="fa fa-info fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">About</span>
                </a>
            </li>

            <li>
                <a href="#">
                    <i class="fa fa-key fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Logout</span>
                </a>
            </li>

        </ul>
    </div>
</nav>

Views/Shared/NavBarFinance(1).cshtml
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
    <div class="sidebar-collapse menu-scroll">
        <ul id="side-menu" class="nav">
            <div class="clearfix"></div>

            <li>
                <a href="@Url.Action("Index", "Finance")">
                    <i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Dashboard</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("FundTable", "Finance")">
                    <i class="fa fa-database fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("ListRequest", "Finance")">
                    <i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Request Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("ReportFunds", "Finance")">
                    <i class="fa fa-file-o fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Report Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("User", "Finance")">
                    <i class="fa fa-user fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">User</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("LogHistory", "Finance")">
                    <i class="fa fa-history fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Log History</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("Guide", "Finance")">
                    <i class="fa fa-search fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Guide</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("About", "Finance")">
                    <i class="fa fa-info fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">About</span>
                </a>
            </li>

            <li>
                <a href="#">
                    <i class="fa fa-key fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Logout</span>
                </a>
            </li>

        </ul>
    </div>
</nav>

Views/Shared/NavBarFinance.cshtml
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
    <div class="sidebar-collapse menu-scroll">
        <ul id="side-menu" class="nav">
            <div class="clearfix"></div>

            <li>
                <a href="@Url.Action("Index", "Finance")">
                    <i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Dashboard</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("FundTable", "Finance")">
                    <i class="fa fa-database fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("ListRequest", "Finance")">
                    <i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Request Funds</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("User", "Finance")">
                    <i class="fa fa-user fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">User</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("LogHistory", "Finance")">
                    <i class="fa fa-history fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Log History</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("Guide", "Finance")">
                    <i class="fa fa-search fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Guide</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("About", "Finance")">
                    <i class="fa fa-info fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">About</span>
                </a>
            </li>

            <li>
                <a href="@Url.Action("Logout","Login")">
                    <i class="fa fa-key fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Logout</span>
                </a>
            </li>

        </ul>
    </div>
</nav>

Views/Shared/NavBarTechnician.cshtml
<nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;" data-position="right" class="navbar-default navbar-static-side">
    <div class="sidebar-collapse menu-scroll">
        <ul id="side-menu" class="nav">
            <div class="clearfix"></div>
            <li>
                <a href="@Url.Action("Index", "Technician")">
                    <i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Dashboard</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("MyProfile", "Technician")">
                    <i class="fa fa-user fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">My Profile</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("RequestFunds", "Technician")">
                    <i class="fa fa-edit fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Request Funds</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("ListRequestFunds", "Technician")">
                    <i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">List Request Funds</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Guide", "Technician")">
                    <i class="fa fa-search fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Guide</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("About", "Technician")">
                    <i class="fa fa-info fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">About</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Logout","Login")">
                    <i class="fa fa-key fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Logout</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

Views/Shared/NavTop (1).cshtml
<nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3" class="navbar navbar-default navbar-static-top">
    <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        <a id="logo" href="index.html" class="navbar-logo"><img src="~/Content/images/logo1.png" width="50px" height="50px" align="center"></a>
    </div>
    <div class="topbar-main">
        <a id="menu-toggle" href="#" class="hidden-xs"><i class="fa fa-bars"></i></a>

    </div>
</nav>

Views/Shared/NavTop(1).cshtml
<nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3" class="navbar navbar-default navbar-static-top">
    <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        <a id="logo" href="index.html" class="navbar-logo"><img src="~/Content/images/logo1.png" width="50px" height="50px" align="center"></a>
    </div>
    <div class="topbar-main">
        <a id="menu-toggle" href="#" class="hidden-xs"><i class="fa fa-bars"></i></a>

    </div>
</nav>