Controllers/DirectorController.cs
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using LPE_Magac.Models;
using LPE_Magac.ViewModel;
using System.Data.Entity.Validation;
using System.Data.Entity;

namespace LPE_Magac.Controllers
{
    [AllowAnonymous]
    public class DirectorController : Controller
    {

        Db_LPE_MagacEntities db = new Db_LPE_MagacEntities();
        // GET: Director
        public ActionResult Index()
        {
            var IOtable = new FundsModel
            {
                Incomes = db.tbl_fund_income.ToList(),
                Outcomes = db.tr_fund_outcome.ToList(),
                Requests = db.tr_fund_request.ToList()
            };
            return View(IOtable);
        }
        public ActionResult GetDataIncome()
        {
            var query = db.tbl_fund_income.GroupBy(p => p.date_income.Value.Year)
                .Select(g => new { date = g.Key, count = g.Sum(x => x.total_fund_income) }).OrderBy(x => x.date).ToList();
            return Json(query, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDataOutcome()
        {
            var query = db.tr_fund_outcome.GroupBy(p => p.date_outcome.Value.Year)
                .Select(g => new { date = g.Key, count = g.Sum(x => x.total_fund_outcome) }).OrderBy(x => x.date).ToList();
            return Json(query, JsonRequestBehavior.AllowGet);
        }
        public ActionResult FundTable()
        {
            var IOtable = new FundsModel
            {
                Incomes = db.tbl_fund_income.ToList(),
                Outcomes = db.tr_fund_outcome.ToList()
            };
            return View(IOtable);
        }
        //=========Req Funds===============
        public ActionResult RequestFunds()
        {
            List<tbl_invoice_director> directors = db.tbl_invoice_director.ToList();
            List<tbl_invoice_finance> invoice = db.tbl_invoice_finance.ToList();
            List<tr_fund_request> request = db.tr_fund_request.ToList();
            var ListRequest = from a in directors
                              join b in invoice on a.fk_id_invoice_finance equals b.pk_id_invoice_finance
                              join c in request on b.fk_id_fund_request equals c.pk_id_fund_request into table
                              from c in table.ToList()
                              select new InvoiceModel
                              {
                                  Invoice_Director = a,
                                  Invoice_Finance = b,
                                  Fund_Request = c
                              };
            return View(ListRequest);
        }
        [HttpGet]
        public ActionResult ApproveListRequest(int id)
        {
            var finance = db.tbl_invoice_finance.Where(x => x.pk_id_invoice_finance == id).FirstOrDefault();
            var id1 = finance.fk_id_fund_request;
            InvoiceModel invoice = new InvoiceModel();
            invoice.Fund_Request = (from b in db.tr_fund_request
                                    where b.pk_id_fund_request == id1
                                    select b).SingleOrDefault();
            invoice.Invoice_Finance = (from b in db.tbl_invoice_finance
                                       where b.pk_id_invoice_finance == id
                                       select b).SingleOrDefault();
            invoice.Invoice_Director = (from b in db.tbl_invoice_director
                                        where b.fk_id_invoice_finance == id
                                        select b).SingleOrDefault();
            return PartialView(invoice);
        }
        [HttpPost]
        public ActionResult ApproveListRequest(int id, InvoiceModel invoice)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var updatedir = db.tbl_invoice_director.Where(x => x.fk_id_invoice_finance == id).FirstOrDefault();
                    updatedir.status_invoice_director = "Approved";
                    updatedir.details = invoice.Invoice_Director.details;
                    db.Entry(updatedir).State = EntityState.Modified;
                    var selectid = db.tbl_invoice_finance.Where(x => x.pk_id_invoice_finance == id).FirstOrDefault();
                    selectid.status_invoice_finance = "App Dir";
                    db.Entry(selectid).State = EntityState.Modified;
                    var idreq = selectid.fk_id_fund_request;
                    var updatereq = db.tr_fund_request.Where(x => x.pk_id_fund_request == idreq).FirstOrDefault();
                    updatereq.status_request = "Approved";
                    db.Entry(updatereq).State = EntityState.Modified;
                    tr_fund_outcome input = new tr_fund_outcome()
                    {
                        service_outcome = updatereq.service_request,
                        date_outcome = updatereq.date_request,
                        applicant_outcome = updatereq.applicant_request,
                        price_per_unit_request = updatereq.price_per_unit_request,
                        quantity_request = updatereq.quantity_request,
                        total_fund_outcome = updatereq.total_value,
                        fk_id_invoice_director = updatedir.pk_id_invoice_director,
                        details_outcome = updatereq.details_request
                    };
                    db.tr_fund_outcome.Add(input);
                    db.SaveChanges();
                    var select = db.tr_fund_outcome.Where(x => x.fk_id_invoice_director == updatedir.pk_id_invoice_director).FirstOrDefault();
                    tbl_finance_report report = new tbl_finance_report()
                    {
                        fk_id_fund_outcome = select.pk_id_fund_outcome,
                        //balance = -(input.total_fund_outcome)
                    };
                    db.tbl_finance_report.Add(report);
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("RequestFunds");
                }
                catch (Exception e)
                {
                    Db_LPE_MagacEntities db1 = new Db_LPE_MagacEntities();
                    tbl_log_history error = new tbl_log_history()
                    {
                        user_name = (string)Session["userName"],
                        fk_id_user = (int)Session["userID"],
                        Action_date = DateTime.Now,
                        ErrorMessage = "Page Error : ApproveListRequest, " + e.Message
                    };
                    db1.tbl_log_history.Add(error);
                    db1.SaveChanges();
                    Transaction.Rollback();
                }
            }
            return View(invoice);
        }
        [HttpGet]
        public ActionResult RejectListRequest(int id)
        {
            var finance = db.tbl_invoice_finance.Where(x => x.pk_id_invoice_finance == id).FirstOrDefault();
            var id1 = finance.fk_id_fund_request;
            InvoiceModel invoice = new InvoiceModel();
            invoice.Fund_Request = (from b in db.tr_fund_request
                                    where b.pk_id_fund_request == id1
                                    select b).SingleOrDefault();
            invoice.Invoice_Finance = (from b in db.tbl_invoice_finance
                                       where b.pk_id_invoice_finance == id
                                       select b).SingleOrDefault();
            invoice.Invoice_Director = (from b in db.tbl_invoice_director
                                        where b.fk_id_invoice_finance == id
                                        select b).SingleOrDefault();
            return PartialView(invoice);
        }
        [HttpPost]
        public ActionResult RejectListRequest(int id, InvoiceModel invoice)
        {
            using (var Transaction = db.Database.BeginTransaction())
            {
                try
                {
                    var selectid = db.tbl_invoice_finance.Where(x => x.pk_id_invoice_finance == id).FirstOrDefault();
                    selectid.status_invoice_finance = "Block";
                    db.Entry(selectid).State = EntityState.Modified;
                    var idreq = selectid.fk_id_fund_request;
                    var updatereq = db.tr_fund_request.Where(x => x.pk_id_fund_request == idreq).FirstOrDefault();
                    updatereq.status_request = "Block";
                    db.Entry(updatereq).State = EntityState.Modified;
                    var selectdir = db.tbl_invoice_director.Where(x => x.fk_id_invoice_finance == id).FirstOrDefault();
                    selectdir.status_invoice_director = "Block";
                    selectdir.details = invoice.Invoice_Director.details;
                    db.Entry(selectdir).State = EntityState.Modified;
                    db.SaveChanges();
                    Transaction.Commit();
                    return RedirectToAction("RequestFunds");
                }
                catch (Exception e)
                {
                    Db_LPE_MagacEntities db1 = new Db_LPE_MagacEntities();
                    tbl_log_history error = new tbl_log_history()
                    {
                        user_name = (string)Session["userName"],
                        fk_id_user = (int)Session["userID"],
                        Action_date = DateTime.Now,
                        ErrorMessage = "Page Error : RejectListRequest, " + e.Message
                    };
                    db1.tbl_log_history.Add(error);
                    db1.SaveChanges();
                    Transaction.Rollback();
                }
            }
            return View(invoice);
        }

        //=============================

Views/Director/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Layout/_Director.cshtml";
}

<!--BEGIN TITLE & BREADCRUMB PAGE-->
<!--BEGIN TITLE & BREADCRUMB PAGE-->
<div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
    <div class="page-header pull-left">
        <div class="page-title">
            Director
        </div>
    </div>
    <ol class="breadcrumb page-breadcrumb pull-right">
        <li><i class="fa fa-home"></i>&nbsp;<a href="#">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="hidden"><a href="#">Dashboard</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="active">About</li>
    </ol>
    <div class="clearfix">
    </div>
</div>
<!--END TITLE & BREADCRUMB PAGE-->
<!--BEGIN CONTENT-->
<div class="page-content">
    <div class="row">
        <div id="tab-general">
            <div class="col-lg-12">
                <div class="col-lg-4">
                    <img src="~/Content/images/logo1.png" style="margin: 60px 60px 60px 60px">
                </div>
                <div class="col-lg-6">
                    <center><h1>Azaz Perusahaan</h1></center>

                    <p>Dalam menjalankan usaha Jasa Inspeksi Teknik tersebut, PT. LINTAS PRIMA ENERGI, menganut Azas Perusahaan yang dituangkan sebagai : VISI, MISI, dan BUDAYA PERUSAHAAN (CORPORATE CULTURE).</p>
                    <p>VISI</p>
                    <ol class="pll">
                        <li>
                            Ikut mewujudkan instalasi ketenagalistrikan di Negara Republik Indonesia memenuhi kriteria Prima, Aman, dan Akrab lingkungan serta Efisien.
                        </li>
                    </ol>
                    <p>MISI</p>
                    <ol class="pll">
                        <li>
                            Menyediakan layanan jasa Inspeksi/Uji Laik Operasi sesuai standar yang berlaku dan memberikan pelayanan secara tepat waktu, tepat mutu dengan biaya yang kompetitif, serta selalu memberikan solusi terhadap masalah
                        </li>
                    </ol>
                </div>
            </div>
            <div class="col-lg-12">
                <h2 class="mbxl">IT Support</h2>
                <div class="row">
                    <div class="col-lg-3">
                        <div class="member-team">
                            <img src="~/Content/images/andi.png" class="img-responsive" />
                            <h3>
                                Andianto Bhakti Nugroho
                                <small>Maintainer</small>
                            </h3>
                            <p>radenabn@gmail.com</p>
                            <ul class="social-icons list-unstyled list-inline mbl mtl">
                                <li><a href="https://www.instagram.com/radenabn/" data-hover="tooltip" data-original-title="instagram" class="instagram"><i class="fa fa-skype"></i></a></li>
                                <li><a href="https://twitter.com/radenabn" data-hover="tooltip" data-original-title="twitter" class="twitter"><i class="fa fa-twitter"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="member-team">
                            <img src="~/Content/images/hafiz.png" class="img-responsive" />
                            <h3>
                                Hafiz Adhiyasa Pratama
                                <small>Maintainer</small>
                            </h3>
                            <p>hafizadhiyasapesat@gmail.com</p>
                            <ul class="social-icons list-unstyled list-inline mbl mtl">
                                <li><a href="https://www.facebook.com/asayihda" data-hover="tooltip" data-original-title="facebook" class="facebook"><i class="fa fa-facebook"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--END CONTENT-->
<!--BEGIN FOOTER-->
<div id="footer">
    <div class="copyright">
        <a href="http://themifycloud.com">2014 © KAdmin Responsive Multi-Purpose Template</a>
    </div>
</div>
<!--END FOOTER-->

Views/Director/ApproveListRequest.cshtml
@model LPE_Magac.ViewModel.InvoiceModel
@{
    ViewBag.Title = "ApproveListRequest";
    Layout = "~/Views/Layout/_Director.cshtml";
}

@using (Html.BeginForm("ApproveListRequest", "Director", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <div class="page-header pull-left">
            <div class="page-title">
                Finance
            </div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
            <li><i class="fa fa-home"></i>&nbsp;<a href="#">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="hidden"><a href="#">List Request</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
            <li class="active">List Request</li>
        </ol>
        <div class="clearfix">
        </div>
    </div>
    <!--END TITLE & BREADCRUMB PAGE-->
    <!--BEGIN CONTENT-->
    <div class="page-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel-body pan">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            Request Fund
                        </div>
                        <div class="panel-body pan">
                            <form action="#">
                                <div class="form-body pal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Fund_Request.pk_id_fund_request)
                                    <div class="form-group">
                                        <label for="inputEmail" class="control-label">
                                            Date
                                        </label>
                                        <div class="input-icon right">
                                            @Html.DisplayName(String.Format("{0:dd/MM/yyyy}", Model.Fund_Request.date_request))
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="Service" class="control-label">
                                            Service
                                        </label>
                                        <div class="input-icon right">
                                            @Html.EditorFor(model => model.Fund_Request.service_request, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputName" class="control-label">
                                            Applicant
                                        </label>
                                        <div class="input-icon right">
                                            @Html.EditorFor(model => model.Fund_Request.applicant_request, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputMessage" class="control-label">
                                            Quantity
                                        </label>
                                        <div class="input-icon right">
                                            @Html.EditorFor(model => model.Fund_Request.quantity_request, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputMessage" class="control-label">
                                            Price/Unit
                                        </label>
                                        <div class="input-icon right">
                                            @Html.EditorFor(model => model.Fund_Request.price_per_unit_request, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputEmail" class="control-label">
                                            Total Funds
                                        </label>
                                        <div class="input-icon right">
                                            @Html.EditorFor(model => model.Fund_Request.total_value, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <label for="inputMessage" class="control-label">
                                            Details
                                        </label>
                                        <div class="input-icon right">
                                            @Html.EditorFor(model => model.Fund_Request.details_request, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputMessage" class="control-label">
                                            Details Approval From Finance
                                        </label>
                                        <div class="input-icon right">
                                            @Html.EditorFor(model => model.Invoice_Finance.details, new { htmlAttributes = new { @class = "form-control", @rows = "5", @style = "width: 1007px; height: 160px;", @readonly = "readonly" } })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputMessage" class="control-label">
                                            Details Approval
                                        </label>
                                        <div class="input-icon right">
                                            @Html.TextAreaFor(model => model.Invoice_Director.details, new { htmlAttributes = new { @class = "form-control", @rows = "5", @style = "width: 1007px; height: 160px;" } })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-actions text-right pal">
                                    <a href=""></a><button type="submit" class="btn btn-primary">Save</button>
                                    @Html.ActionLink("Back to List", "RequestFunds")
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<!--END CONTENT-->
<!--BEGIN FOOTER-->
<div id="footer">
    <div class="copyright">
        <a href="http://themifycloud.com">2014 © KAdmin Responsive Multi-Purpose Template</a>
    </div>
</div>
<!--END FOOTER-->

Views/Director/FundTable.cshtml
@model LPE_Magac.ViewModel.FundsModel

@{
    ViewBag.Title = "FundTable";
    Layout = "~/Views/Layout/_Director.cshtml";
    int a = 0;
    int b = 0;
}

<!--BEGIN TITLE & BREADCRUMB PAGE-->
<div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
    <div class="page-header pull-left">
        <div class="page-title">
            Director
        </div>
    </div>
    <ol class="breadcrumb page-breadcrumb pull-right">
        <li><i class="fa fa-home"></i>&nbsp;<a href="#">Home</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="hidden"><a href="#">Funds</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="active">Funds</li>
    </ol>
    <div class="clearfix">
    </div>
</div>
<!--END TITLE & BREADCRUMB PAGE-->
<!--BEGIN CONTENT-->
<div class="page-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    Income
                </div>
                <div class="panel-body">
                    <div class="btn-group pull-right">
                        <a href="@Url.Action("ViewIncome", "Director")" target="_blank"><button class="btn btn">Print or Save PDF<i class="icon-plus icon-white"></i></button></a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="example1" class="table table-hover">
                            <thead style="text-align: center;">
                                <tr>
                                    <th style="text-align: center;">No</th>
                                    <th style="text-align: center;">Date</th>
                                    <th style="text-align: center;">Service</th>
                                    <th style="text-align: center;">Applicant</th>
                                    <th style="text-align: center;">Total Funds</th>
                                    <th style="text-align: center;">Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Incomes.Reverse())
                                {
                                    <tr>
                                        <td style="text-align: center;">
                                            <span>@(++a)</span>
                                        </td>
                                        <td>
                                            @Html.DisplayName(String.Format("{0:dd/MM/yyyy}", @item.date_income))
                                        </td>
                                        <td>
                                            @item.service_income
                                        </td>
                                        <td>
                                            @item.applicant_income
                                        </td>
                                        <td>
                                            @Html.DisplayFor(Modelitem => item.total_fund_income, new { htmlAttributes = new { @id = "rupiah" } })
                                        </td>
                                        <td>
                                            @item.details_income
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    Outcome
                </div>
                <div class="panel-body">
                    <div class="btn-group">
                        <a href="@Url.Action("FormOutcome", "Director")"><button class="btn btn-success">Request Fund<i class="icon-plus icon-white"></i></button></a>
                    </div>
                    <div class="btn-group pull-right">
                        <a href="@Url.Action("ViewOutcome", "Director")" target="_blank"><button class="btn btn">Print or Save PDF<i class="icon-plus icon-white"></i></button></a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="example2" class="table table-hover">
                            <thead>
                                <tr>
                                    <th style="text-align: center;">No</th>
                                    <th style="text-align: center;">Date</th>
                                    <th style="text-align: center;">Service</th>
                                    <th style="text-align: center;">Applicant</th>
                                    <th style="text-align: center;">Price/Unit</th>
                                    <th style="text-align: center;">Quantity</th>
                                    <th style="text-align: center;">Total Funds</th>
                                    <th style="text-align: center;">Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Outcomes.Reverse())
                                {
                                    <tr>
                                        <td style="text-align: center;">
                                            <span>@(++b)</span>
                                        </td>
                                        <td>
                                            @Html.DisplayName(String.Format("{0:dd/MM/yyyy}", @item.date_outcome))
                                        </td>
                                        <td>
                                            @item.service_outcome
                                        </td>
                                        <td>
                                            <!--user-->
                                            @item.applicant_outcome
                                        </td>
                                        <td>
                                            @Html.DisplayFor(Modelitem => item.price_per_unit_request, new { htmlAttributes = new { @id = "rupiah" } })
                                        </td>
                                        <td style="text-align: center;">
                                            @item.quantity_request
                                        </td>
                                        <td>
                                            @Html.DisplayFor(Modelitem => item.total_fund_outcome, new { htmlAttributes = new { @id = "rupiah" } })
                                        </td>
                                        <td>
                                            @item.details_outcome
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--END CONTENT-->
<!--BEGIN FOOTER-->
<div id="footer">
    <div class="copyright">
        <a href="http://themifycloud.com">2014 © KAdmin Responsive Multi-Purpose Template</a>
    </div>
</div>
<!--END FOOTER-->

Views/Director/ViewIncome.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "ViewIncome";
    Layout = "~/Views/Layout/_Report.cshtml";
}
<h2>Income</h2>
@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer);

Views/Director/ViewOutcome.cshtml
@using ReportViewerForMvc;
@{
    ViewBag.Title = "ViewIncome";
    Layout = "~/Views/Layout/_Report.cshtml";
}
<h2>Income</h2>
@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer);